# frozen_string_literal: true

require_relative 'portland/attr_reader'
require_relative 'portland/attr_writer'
require_relative 'portland/begin_end_block'
require_relative 'portland/bitwise'
require_relative 'portland/class_variable'
require_relative 'portland/eval_family'
require_relative 'portland/fetch'
require_relative 'portland/flip_flop'
require_relative 'portland/for_loop'
require_relative 'portland/freeze_family'
require_relative 'portland/global_variable'
require_relative 'portland/in_place_mutator'
require_relative 'portland/inheritance'
require_relative 'portland/instance_variable_read'
require_relative 'portland/instance_variable_write'
require_relative 'portland/method_missing'
require_relative 'portland/numbered_parameter'
require_relative 'portland/raise_rescue'
require_relative 'portland/regex'
require_relative 'portland/require_by_name'
require_relative 'portland/runtime_define_method'
require_relative 'portland/shift_append'
require_relative 'portland/singleton_class'
require_relative 'portland/splat'
require_relative 'portland/thread_model'
require_relative 'portland/visibility'
